[tool.black]
line-length = 150
target-version = ['py37']
skip-string-normalization = true
exclude = '''
(
  /(
      \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | migrations
    | backup
    | venv
    | site-packages
  )/
)
'''
fast = true