indent-width = 4
line-length = 120

target-version = "py310"
respect-gitignore = true

[format]
quote-style = "double"

[lint]
select = ["E", "F", "I", "UP", "Q"]

[lint.isort]
known-first-party = []
combine-as-imports = true
lines-after-imports = 2
